services:
  db:
    image: postgres:15-alpine
    container_name: wallet-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: wallet-mq
    ports:
      - "${MQ_PORT_GO}:5672" # Backend
      - "${MQ_PORT_DASHBOARD}:15672" # Dashboard
    environment:
      RABBITMQ_DEFAULT_USER: ${MQ_USER}
      RABBITMQ_DEFAULT_PASSWORD: ${MQ_PASSWORD}

volumes:
  postgres_data:

